import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {ConnectorsPanel,ConnectorInbox} from './ConnectorsPanel';
const status={mailbox:{provider:null,address:null,connected:false,paused:true,lastSync:null,error:null},sms:{configured:false,enabled:false,fromNumber:null,webhookUrl:'https://fixture.example/webhooks/twilio/sms',statusCallbackUrl:'https://fixture.example/webhooks/twilio/sms/status'},selection:null,providers:[{provider:'gmail',available:true,callbackUrl:'https://fixture.example/api/connectors/oauth/gmail/callback'},{provider:'outlook',available:false,callbackUrl:'https://fixture.example/api/connectors/oauth/outlook/callback'}]};
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();});
function requests(){const fetch=vi.fn(async(input:RequestInfo|URL)=>{const url=String(input);return Response.json(url.endsWith('/preferences')?{emailEnabled:false,emailVerified:false,smsEnabled:false,smsVerified:false,smsOptedOut:false}:url.endsWith('/connections')?{connections:[]}:url.endsWith('/messages')?{messages:[{id:'one',channel:'sms',direction:'in',body:'Private fixture message',status:'replied',created_at:new Date().toISOString()}]}:status);});vi.stubGlobal('fetch',fetch);return fetch;}
describe('Connectors settings and private history',()=>{
 it('shows the three guided cards with no credential forms for members',async()=>{requests();render(<ConnectorsPanel administrator={false} csrfToken="fixture"/>);expect(await screen.findByRole('heading',{name:'Gmail'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Outlook'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Twilio SMS'})).toBeInTheDocument();expect(screen.queryByLabelText('Auth token')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Send test message'})).not.toBeInTheDocument();expect(screen.getByLabelText('Email conversations and updates')).toBeDisabled();});
 it('requires an explicit test action and never sends on render',async()=>{const fetch=requests();render(<ConnectorsPanel administrator csrfToken="fixture"/>);await screen.findByRole('button',{name:'Send test message'});expect(fetch.mock.calls.some(c=>String(c[0]).endsWith('/test'))).toBe(false);expect(screen.getAllByLabelText('Client secret')).toHaveLength(2);});
 it('loads only the authenticated member history and closes without mutating it',async()=>{const fetch=requests(),close=vi.fn();render(<ConnectorInbox csrfToken="fixture" onClose={close}/>);expect(await screen.findByText('Private fixture message')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Close messages'}));expect(close).toHaveBeenCalledOnce();expect(fetch.mock.calls.every(c=>String(c[0])==='/api/connectors/messages')).toBe(true);});
});
