import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { MoreHorizontal } from "lucide-react";
import "./item-actions.css";
export type ItemAction = { label: string; run: () => void | Promise<unknown>; disabled?: boolean; reason?: string; confirm?: string; danger?: boolean };
export function ItemActions({ name, actions, children }: { name: string; actions: ItemAction[]; children?: ReactNode }) {
 const [position,setPosition]=useState<{x:number;y:number}>();const [confirmation,setConfirmation]=useState<ItemAction>();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const menu=useRef<HTMLDivElement>(null);const dialog=useRef<HTMLDialogElement>(null);const anchor=useRef<HTMLElement|null>(null);
 function close(){setPosition(undefined);anchor.current?.focus();}
 function open(x:number,y:number,target:HTMLElement){if(busy)return;anchor.current=target;setError("");setPosition({x,y});}
 useLayoutEffect(()=>{if(!position||!menu.current)return;const el=menu.current;el.style.left=`${Math.max(8,Math.min(position.x,window.innerWidth-el.offsetWidth-8))}px`;el.style.top=`${Math.max(8,Math.min(position.y,window.innerHeight-el.offsetHeight-8))}px`;el.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();},[position]);
 useEffect(()=>{if(!position)return;const dismiss=(e:Event)=>{if(!menu.current?.contains(e.target as Node))close();};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',escape);window.addEventListener('resize',close);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',escape);window.removeEventListener('resize',close);};},[position]);
 useEffect(()=>{if(confirmation){dialog.current?.showModal();dialog.current?.querySelector<HTMLButtonElement>('[data-cancel]')?.focus();}},[confirmation]);
 async function execute(action:ItemAction){if(busy)return;setBusy(true);setError("");try{await action.run();setConfirmation(undefined);close();}catch(e){setError(e instanceof Error?e.message:'The action could not be completed.');}finally{setBusy(false);}}
 return <div className="item-actions" onContextMenu={e=>{e.preventDefault();e.stopPropagation();open(e.clientX,e.clientY,(e.target as HTMLElement).closest<HTMLElement>('button,[tabindex]')??e.currentTarget);}} onKeyDown={e=>{if((e.shiftKey&&e.key==='F10')||e.key==='ContextMenu'){e.preventDefault();const r=e.currentTarget.getBoundingClientRect();open(r.left+24,r.top+24,e.target as HTMLElement);}}}>
 {children}<button type="button" className="item-actions-trigger" aria-label={`Actions for ${name}`} aria-haspopup="menu" aria-expanded={Boolean(position)} disabled={busy} onClick={e=>{e.stopPropagation();const r=e.currentTarget.getBoundingClientRect();open(r.left,r.bottom,e.currentTarget);}}><MoreHorizontal /></button>
 {position&&createPortal(<div ref={menu} role="menu" aria-label={`${name} actions`} className="item-action-menu" style={{left:position.x,top:position.y}} onKeyDown={e=>{const buttons=[...e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];let i=buttons.indexOf(document.activeElement as HTMLButtonElement);if(['ArrowDown','ArrowUp','Home','End','Tab'].includes(e.key)){e.preventDefault();if(e.key==='Tab'){close();return;}i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[i]?.focus();}}}>
 {actions.map(a=><button type="button" role="menuitem" key={a.label} disabled={a.disabled||busy} title={a.reason} className={a.danger?'is-danger':''} onClick={()=>{if(a.confirm){setPosition(undefined);setConfirmation(a);}else void execute(a);}}>{a.label}{a.disabled&&a.reason&&<small>{a.reason}</small>}</button>)}{error&&<p role="alert">{error}</p>}</div>,document.body)}
 {confirmation&&createPortal(<dialog ref={dialog} className="item-action-dialog" aria-labelledby="item-delete-title" onCancel={e=>{e.preventDefault();if(!busy){setConfirmation(undefined);close();}}}><h2 id="item-delete-title">Delete “{name}”?</h2><p>{confirmation.confirm}</p>{error&&<p role="alert">{error}</p>}<footer><button data-cancel type="button" disabled={busy} onClick={()=>{setConfirmation(undefined);close();}}>Cancel</button><button type="button" className="is-danger" disabled={busy} onClick={()=>void execute(confirmation)}>{busy?'Deleting…':'Delete'}</button></footer></dialog>,document.body)}
 </div>;
}
