import { describe,it,expect,vi } from 'vitest';
import { authenticatedSender, emailAddress, MailProviders, oauthStart } from '../src/mailProviders.js';
import { validTwilioSignature } from '../src/connectors.js';
import { createHmac } from 'node:crypto';
const token={accessToken:'fixture-only',refreshToken:'fixture-refresh',expiresAt:Date.now()+3600000};
describe('mail and SMS provider boundaries',()=>{
 it('uses offline OAuth, state and PKCE without putting secrets in the consent URL',()=>{for(const provider of ['gmail','outlook'] as const){const r=oauthStart(provider,{clientId:'public',clientSecret:'secret-fixture'},'https://example.org/callback','state-fixture');const url=new URL(r.url);expect(url.searchParams.get('state')).toBe('state-fixture');expect(url.searchParams.get('code_challenge_method')).toBe('S256');expect(r.url).not.toContain('secret-fixture');expect(r.verifier.length).toBeGreaterThan(30);}});
 it('does not accept sender-controlled lower authentication results or domain lookalikes',()=>{const good={name:'Authentication-Results',value:'mx.google.com; dmarc=pass header.from=example.org'};expect(authenticatedSender([good],'a@example.org','gmail')).toBe(true);expect(authenticatedSender([{...good,value:'mx.google.com; dmarc=fail header.from=example.org'},good],'a@example.org','gmail')).toBe(false);expect(authenticatedSender([good],'a@other.example.org','gmail')).toBe(false);expect(authenticatedSender([{...good,value:'untrusted.example; dmarc=pass header.from=example.org'}],'a@example.org','gmail')).toBe(false);expect(authenticatedSender([{...good,value:'spf=pass; dmarc=pass action=none header.from=example.org; compauth=pass reason=100'}],'a@example.org','outlook')).toBe(true);});
 it('rejects arbitrary Graph continuation URLs before making a request',async()=>{const fn=vi.fn();const service=new MailProviders(fn);await expect(service.json('outlook',token,'https://private.example/steal')).rejects.toThrow('invalid_provider_cursor');expect(fn).not.toHaveBeenCalled();});
 it('baselines existing Gmail mail without replaying it',async()=>{const fn=vi.fn(async()=>Response.json({historyId:'123'}));expect(await new MailProviders(fn).poll('gmail',token,null)).toEqual({messages:[],cursor:{history:'123'}});expect(fn).toHaveBeenCalledOnce();});
 it('baselines all Outlook pages and does not reply to historical mail',async()=>{const fn=vi.fn(async()=>Response.json({value:[{id:'old',body:{content:'old'}}],'@odata.deltaLink':'https://graph.microsoft.com/v1.0/delta?token=x'}));expect((await new MailProviders(fn).poll('outlook',token,null)).messages).toEqual([]);});
 it('includes all webhook fields and the exact externally configured URL in signatures',()=>{const fields={Body:'hello',From:'+15555550100',Extra:'new-field'};const url='https://workspace.example/webhooks/twilio/sms';const signature=createHmac('sha1','fixture').update(url+Object.keys(fields).sort().map(k=>k+fields[k as keyof typeof fields]).join('')).digest('base64');expect(validTwilioSignature('fixture',url,fields,signature)).toBe(true);expect(validTwilioSignature('fixture',url+'/status',fields,signature)).toBe(false);expect(validTwilioSignature('fixture',url,{...fields,Body:['hello','changed']},signature)).toBe(false);});
 it('does not allow address header injection',()=>{expect(emailAddress('Name <member@example.org>')).toBe('member@example.org');expect(emailAddress('a@example.org\r\nBcc: b@example.org')).toBe('');});
});
